# Generated by Django 4.2.5 on 2023-09-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_post_options_post_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='sluge',
        ),
    ]
