# Generated by Django 4.2.5 on 2023-10-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('slug', models.SlugField(unique=True)),
                ('date_created', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('author', models.ManyToManyField(to='blogs.artist')),
                ('categories', models.ManyToManyField(to='blogs.category')),
            ],
        ),
    ]
