# Generated by Django 4.2.5 on 2023-10-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='album',
            field=models.ManyToManyField(to='blogs.album'),
        ),
    ]
