# Generated by Django 4.2.5 on 2023-10-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_remove_post_slug_post_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='overview',
        ),
    ]
