# Generated by Django 4.2.5 on 2023-10-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_remove_album_author_album_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='blogs.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_created',
            field=models.DateField(),
        ),
    ]
