# Generated by Django 4.2.5 on 2023-10-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_remove_post_album_post_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
